server:
  port: 8086

order:
  service:
    base-url: http://order-service

spring:
  application:
    name: payment-service

  datasource:
    url: jdbc:mysql://localhost:3306/paymentdb
    username: root
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        spring.json.add.type.headers: false
        spring.json.trusted.packages: "com.store.dto.*"

app:
  # Topics tái sử dụng cách đặt tên bạn đang dùng
  topics:
    paymentSucceeded: payment.succeeded
    paymentFailed: payment.failed
    paymentIntentCreate: payment-intent-create
  mock:
    enable: true   # bật trang mockpay/checkout để test local

jwt:
  secret: Y3ZndQGRXwfnr+Ub6sCBDkri7Z1z8refHJYaaO42OZnyh1d70pHAV7it+bh/81rM

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
paypal:
  base-url: https://api-m.sandbox.paypal.com
  client-id: AQEyZlrsnBTPjoncAA81bI0hACMc4TJiw80mJPQzpqEzwa78i6LDqoqj9rAdJSCWRZVS2XjSIYQYSI-W
  client-secret: EICy2Tnhfc7at9Tvz3BS5RMSo4Y1owC0B32ekwYvT7ecCr8zg1w8-phRZrhjf27d_sJIhp6AgW5zbh1D
  return-url: http://localhost:8086/paypal/return
  cancel-url:  http://localhost:8086/paypal/cancel